Acme\MainBundle\Entity\Comment:
    type:  entity
    table: comments
    repositoryClass: Acme\MainBundle\Entity\CommentRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        email:
            type: string
            length: 100
        text:
            type: string
            lenght: 500
        updated:
            type: datetime
            nullable: TRUE
        created:
            type: datetime
    manyToOne:
        post:
            targetEntity: Acme\MainBundle\Entity\Post
            inversedBy: comments
            joinColumn:
                name: post_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks:
        prePersist: [setCreatedValue]
        preUpdate:  [setUpdatedValue]
