Acme\MainBundle\Entity\Tag:
    type:  entity
    table: tags
    repositoryClass: Acme\MainBundle\Entity\TagRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        updated:
            type: datetime
            nullable: TRUE
        created:
            type: datetime
    manyToMany:
        posts:
            targetEntity: Acme\MainBundle\Entity\Post
            mappedBy: tags
    lifecycleCallbacks:
        prePersist: [setCreatedValue]
        preUpdate:  [setUpdatedValue]
